<robot name="mycar" xmlns:xacro="http://wiki.ros.org/xacro">
<!-- 摄像头 -->
    <!-- 
        参数：
        link长宽高
        joint关jie:xyz
     -->
     <!-- 厚度 -->
    <xacro:property name="camera_length" value="0.01"/>  
    <xacro:property name="camera_width" value="0.02"/>  
    <xacro:property name="camera_height" value="0.02"/>  
    <xacro:property name="joint_camera_x" value="0.08"/>  
    <xacro:property name="joint_camera_y" value="0"/> 
    <xacro:property name="joint_camera_z" value="${base_length/2+camera_height/2}"/>  

    <link name="camera">
        <visual>
            <geometry>
                <box size="${camera_length} ${camera_width} ${camera_height}"/>
            </geometry>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <material name="black">
                <color rgba="0.0 0.0 0.0 0.8"/>
            </material>
        </visual>
    </link>

    <joint name="camera2base" type="fixed">
        <parent link="base_link"/>
        <child link="camera"/>
        <origin xyz="${joint_camera_x} ${joint_camera_y} ${joint_camera_z}" rpy="0.0 0.0 0.0"/>
    </joint>



</robot>