<robot name="mycar" xmlns:xacro="http://wiki.ros.org/xacro">
    <xacro:property name="PI" value="3.1415927"/>
    <xacro:property name="radius" value="0.03"/>

    <!-- diaoyong -->
    <myuse name="${PI}"/>
    <myuse name="${radius}"/>


    <myuse result="${PI/2}"/>
    <myuse name="${radius*2}"/>
</robot>