<robot name="mycar" xmlns:xacro="http://wiki.ros.org/xacro">
    <!--%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% -->
    <xacro:property name="footprint_radius" value="0.001"/>
    <link name="base_footprint">
        <visual>
            <geometry>
                <sphere radius="${footprint_radius}"/>
            </geometry>
        </visual>
    </link>
    <xacro:property name="base_radius" value="0.1"/>
    <xacro:property name="base_length" value="0.08"/>
    <xacro:property name="lidi" value="0.015"/>
    <xacro:property name="base_joint_z" value="${base_length/2+lidi}"/>

     <!-- dipan 圆柱 0.1米高0.08m,离地0.015m-->
    <link name="base_link">
        <visual>
            <geometry>
                <cylinder radius="0.1" length="0.08"/>
            </geometry>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <material name="base_linkcolor">
                <color rgba="0.8 0.4 0.1 0.5"/>
            </material>
        </visual>
    </link>
    <!-- joint -->
    <joint name="link2footprint" type="fixed">
        <parent link="base_footprint"/>
        <child link="base_link"/>
        <origin xyz="0.0 0.0 0.055" rpy="0.0 0.0 0.0"/>
    </joint>
<!-- ###################################################### -->
    <!-- 驱动轮 圆柱 0.035m半径，宽度0.015m-->
    <xacro:property name="wheel_radius" value="0.0325"/>
    <xacro:property name="wheel_length" value="0.015"/>
    <xacro:property name="PI" value="3.1515927"/>
    <!-- 注意结果是负数 -->
    <xacro:property name="wheel_joint_z" value="${(base_length/2+lidi-wheel_radius)* -1}"/>
    <!-- 
        wheel_name: left or right
        flag: -1 or 1

     -->
    <xacro:macro name="wheel_fucn" params="wheel_name flag">
        <link name="${wheel_name}_wheel">
            <visual>
                <geometry>
                    <cylinder radius="0.0325" length="0.015"/>
                </geometry>
                <origin xyz="0.0 0.0 0.0" rpy="1.5708 0.0 0.0"/>
                <material name="left_wheel">
                    <color rgba="0.0 0.0 0.0 0.3"/>
                </material>
            </visual>
        </link>
        <joint name="${wheel_name}2link" type="continuous">
            <parent link="base_link"/>
            <child link="${wheel_name}_wheel"/>
            <origin xyz="0.0 ${0.1 * flag} -0.0225" rpy="0.0 0.0 0.0"/>
            <axis xyz="0.0 1 0.0"/>
        </joint>
    </xacro:macro>

    <xacro:wheel_fucn wheel_name="left" flag="1"/>
    <xacro:wheel_fucn wheel_name="right" flag="-1"/>
    <!-- %%%%%%%%%%%%%%%%%%%%%%%%%% -->
    <!-- ######################################################-->
        <!-- 万向轮 -->
    <xacro:property name="small_wheel_radius" value="0.0075"/>
    <xacro:property name="small_joint_z" value="${(base_length/2+lidi-small_wheel_radius)* -1}"/>
    <xacro:macro name="small_wheel_fucn" params="small_wheel_name flag">
        <link name="${small_wheel_name}_wheel">
            <visual>
                <geometry>
                    <sphere radius="0.0075"/>
                </geometry>
                <origin xyz="0.0 0.0 0.0" rpy="0 0.0 0.0"/>
                <material name="right_wheel">
                    <color rgba="0.0 0.0 0.0 0.3"/>
                </material>
            </visual>
        </link>
        <joint name="${small_wheel_name}2link" type="continuous">
            <parent link="base_link"/>
            <child link="${small_wheel_name}_wheel"/>
            <origin xyz="${0.08 *flag} 0 ${small_joint_z}" rpy="0.0 0.0 0.0"/>
            <axis xyz="0.0 1 0.0"/>
        </joint>
    </xacro:macro>
    <xacro:small_wheel_fucn small_wheel_name="front" flag="1"/>
    <xacro:small_wheel_fucn small_wheel_name="back" flag="-1"/>


</robot>